name: Rebase

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  rebase:
    name: Rebase and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: fork-release

      - name: Set Git Info
        run: |
          git config --global user.email aleisa.naser@gmail.com
          git config --global user.name "Naser Aleisa"
          git remote add upstream https://github.com/antfu/eslint-config.git

      - name: Rebase and Push
        run: |
          git fetch upstream main:main
          git rebase upstream/main
          git push -f
